### PR TITLE
Moved files into test dir. Starting on mods to make run in test/.

### PR DESCRIPTION
**Pull request by MBARIMike**

### CODE REVIEW

**Comment by MBARIMike** [comment]
When I try running test/functional_tests.sh I get:

```
mkdir: cannot create directory ‘/home/mccann/dev/banzaigit/test/processed/Analysis_20160314_1459’: No such file or directory
tee: /home/mccann/dev/banzaigit/test/processed/Analysis_20160314_1459/logfile.txt: No such file or directory
```

I'll see if I can fix that and see it can get a little further...

**Comment by MBARIMike** [comment]
@reikopm: I got a little further. Now I get this:

```
Warning: Library directories and library names in metadata are NOT the same. Something will probably go wrong later...
LIB_TAG_MOD
BOG18S_banzai.sh: line 250: LIB_TAG_MOD: command not found
```

**Comment by reikopm** [comment]
That should be okay.  It means that there are more library subdirectories found than are mentioned in the metadata file.  Because this is a test I only included a few data files and not the whole data set which would take a long time to process.

```
  From: Mike McCann <notifications@github.com>
```

 To: reikopm/banzai banzai@noreply.github.com 
Cc: reikopm reikopm@yahoo.com
 Sent: Monday, March 14, 2016 3:13 PM
 Subject: Re: [banzai] Moved files into test dir. Starting on mods to make run in test/. (#1)

@reikopm: I got a little further. Now I get this:Warning: Library directories and library names in metadata are NOT the same. Something will probably go wrong later...
LIB_TAG_MOD
BOG18S_banzai.sh: line 250: LIB_TAG_MOD: command not found

**Comment by MBARIMike** [comment]
Now I get this error:

```
python: can't open file '/home/mccann/dev/banzaigit/dereplication/dereplicate_fasta.py': [Errno 2] No such file or directory
```

**Comment by MBARIMike** [comment]
dereplicate_fasta.py doesn't seem to be in the repo.

**Comment by MBARIMike** [comment]
It looks like @jimmyodonnell added the dereplication directory and this branch doesn't have it. I tried merging it with:

```
git remote add -f upstream https://github.com/jimmyodonnell/banzai.git
git pull upstream master
```

but get these errors:

```
[mccann@mbonlive banzaigit]$ git pull upstream master
From https://github.com/jimmyodonnell/banzai
 * branch            master     -> FETCH_HEAD
Auto-merging analyses_prelim.R
CONFLICT (add/add): Merge conflict in analyses_prelim.R
Auto-merging README.md
CONFLICT (add/add): Merge conflict in README.md
Automatic merge failed; fix conflicts and then commit the result.
```

**Comment by reikopm** [comment]
I added some code to analyses_prelim.rI should have renamed it to analyses_prelim_reiko.r
-R

```
  From: Mike McCann <notifications@github.com>
```

 To: reikopm/banzai banzai@noreply.github.com 
Cc: reikopm reikopm@yahoo.com
 Sent: Tuesday, March 15, 2016 8:32 AM
 Subject: Re: [banzai] Moved files into test dir. Starting on mods to make run in test/. (#1)

It looks like @jimmyodonnell added the dereplication directory and this branch doesn't have it. I tried merging it with:git remote add -f upstream https://github.com/jimmyodonnell/banzai.git
git pull upstream master
but get these errors:[mccann@mbonlive banzaigit]$ git pull upstream master
From https://github.com/jimmyodonnell/banzai
- branch            master     -> FETCH_HEAD
  Auto-merging analyses_prelim.R
  CONFLICT (add/add): Merge conflict in analyses_prelim.R
  Auto-merging README.md
  CONFLICT (add/add): Merge conflict in README.md
  Automatic merge failed; fix conflicts and then commit the result.

**Comment by MBARIMike** [comment]
Here's what I just did after encountering that merge conflict:

```
git merge --abort
```

Moved `analyses_prelim.R` and `README.md` to `_reiko` names. Committed them, then did:

```
git pull upstream master
```

**Comment by MBARIMike** [comment]
The `test/functional_tests.sh` execution now takes several minutes on mbonlive with this output at the end:

```
10:15 Create new otu tables with Phinch style ranks
 Merge taxonomy to OTU table.  Does not include no hits, not assigned.  Output is OTU_table_taxa_phinch.txt with Phinch prefixes denoting taxonomic rank.  i.e. p__Proteobacteria
python: can't open file 'merge_otu_taxa2.py': [Errno 2] No such file or directory
sed: can't read /home/mccann/dev/banzaigit/test/processed/Analysis_20160315_1010/all_lib/OTU_table_taxa_phinch.txt: No such file or directory
python: can't open file 'merge_otu_taxa_all.py': [Errno 2] No such file or directory
10:15 Create biom file BOG18S.biom
Usage: biom convert [OPTIONS]

Error: Invalid value for "-i" / "--input-fp": Path "/home/mccann/dev/banzaigit/test/processed/Analysis_20160315_1010/all_lib/OTUs_swarm/OTU_table.txt" does not exist.
Usage: biom convert [OPTIONS]

Error: Invalid value for "-i" / "--input-fp": Path "/home/mccann/dev/banzaigit/test/processed/Analysis_20160315_1010/all_lib/OTUs_swarm/OTU_table.txt" does not exist.
Usage: biom add-metadata [OPTIONS]

Error: Invalid value for "-i" / "--input-fp": Path "/home/mccann/dev/banzaigit/test/processed/Analysis_20160315_1010/all_lib/BOG18S_json.biom" does not exist.
Usage: biom add-metadata [OPTIONS]

Error: Invalid value for "-i" / "--input-fp": Path "/home/mccann/dev/banzaigit/test/processed/Analysis_20160315_1010/all_lib/BOG18S_hdf5.biom" does not exist.
Usage: biom add-metadata [OPTIONS]

Error: Invalid value for "-i" / "--input-fp": Path "/home/mccann/dev/banzaigit/test/processed/Analysis_20160315_1010/all_lib/BOG18S_hdf5_md.biom" does not exist.
Usage: biom add-metadata [OPTIONS]

Error: Invalid value for "-i" / "--input-fp": Path "/home/mccann/dev/banzaigit/test/processed/Analysis_20160315_1010/all_lib/BOG18S_json_md.biom" does not exist.
Create a PEAR report with the names of the read files and the assembled, discarded, and not assembled read numbers.  The report also includes the PEAR parameters
mk_PEAR_report.py  /home/mccann/dev/banzaigit/test/processed/Analysis_20160315_1010
python: can't open file 'mk_PEAR_report.py': [Errno 2] No such file or directory
Pipeline finished! Started at 20160315_1010 and finished at 20160315_1015
Data are in  /home/mccann/dev/banzaigit/test/processed/Analysis_20160315_1010
```

**Comment by MBARIMike** [comment]
@reikopm: It looks like some more (beyond preliminary) analysis is done in these [lines](https://github.com/MBARIMike/banzai/blob/7c799a624480a5a97e4d62c832e2f0b17c23ee25/BOG18S_banzai.sh#L1138-L1193) where the python scripts (that aren't found in the previous comment) are executed. It's generally a good idea to minimize the number of files in the root of the project's directory. What should be the name of a new directory for these "analysis" -type scripts?

**Comment by MBARIMike** [comment]
Seems to get a little further and is apparently using the 18S_test_data database from @kevanMBARI. Getting this error message now:

```
15:46 Create new otu tables with Phinch style ranks
 Merge taxonomy to OTU table.  Does not include no hits, not assigned.  Output is OTU_table_taxa_phinch.txt with Phinch prefixes denoting taxonomic rank.  i.e. p__Proteobacteria
Traceback (most recent call last):
  File "/home/mccann/dev/banzaigit/python/merge_otu_taxa2.py", line 43, in <module>
    main(sys.argv[1:])
  File "/home/mccann/dev/banzaigit/python/merge_otu_taxa2.py", line 27, in main
    with open('./OTUs_swarm/OTU_table.txt', 'r') as f2:
IOError: [Errno 2] No such file or directory: './OTUs_swarm/OTU_table.txt'
sed: can't read /home/mccann/dev/banzaigit/test/processed/Analysis_20160315_1545/all_lib/OTU_table_taxa_phinch.txt: No such file or directory
Traceback (most recent call last):
  File "/home/mccann/dev/banzaigit/python/merge_otu_taxa_all.py", line 43, in <module>
    main(sys.argv[1:])
  File "/home/mccann/dev/banzaigit/python/merge_otu_taxa_all.py", line 32, in main
    with open('./OTUs_swarm/OTU_table.txt', 'r') as f2:
IOError: [Errno 2] No such file or directory: './OTUs_swarm/OTU_table.txt'
```

**Comment by MBARIMike** [comment]
@reikopm The errors I'm getting now are in the biom file creation steps that you added. Perhaps it's time for you to merge these commits into your branch so that you can pull them to your working directory for testing and modification. I suspect problems will be due to me moving the processing to the test directory.

**Comment by reikopm** [comment]
will do

```
  From: Mike McCann <notifications@github.com>
```

 To: reikopm/banzai banzai@noreply.github.com 
Cc: reikopm reikopm@yahoo.com
 Sent: Tuesday, March 15, 2016 4:56 PM
 Subject: Re: [banzai] Moved files into test dir. Starting on mods to make run in test/. (#1)

@reikopm The errors I'm getting now are in the biom file creation steps that you added. Perhaps it's time for you to merge these commits into your branch so that you can pull them to your working directory for testing and modification. I suspect problems will be due to me moving the processing to the test directory.—

**Comment by MBARIMike** [comment]
@reikopm I pulled this branch onto another VM hoping that we'd have self-contained test and database data in the test/ directory so that test/functional_tests.sh would work anywhere. It didn't. There's a PARENT_DIR setting in test/BOG_kelp18S/BOG_kelp18S_params.sh that points to a share on the mbonlive server.

**Comment by reikopm** [comment]
re: PARENT_DIR
Modifications to BOG_kelp18S_params.sh:
move HOME_DIR assignment above PARENT_DIR assignment. Created appropriate subdirectories for BOG_kelp18S C libraries and moved fastq files the libraries C1 and C2

# Use test direcory for source data and for work area

CURR_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
HOME_DIR=$(dirname $CURR_DIR)

# What is the file path to the directory containing all of the libraries/reads?

# In this version the PARENT_DIR is passed in to banzai_BOG18S.sh

PARENT_DIR="$HOME_DIR/raw/BOG_kelp18S/C"

I will work the biom file processing modifications next.

```
  From: Mike McCann <notifications@github.com>
```

 To: reikopm/banzai banzai@noreply.github.com 
Cc: reikopm reikopm@yahoo.com
 Sent: Wednesday, March 16, 2016 3:04 PM
 Subject: Re: [banzai] Moved files into test dir. Starting on mods to make run in test/. (#1)

@reikopm I pulled this branch onto another VM hoping that we'd have self-contained test and database data in the test/ directory so that test/functional_tests.sh would work anywhere. It didn't. There's a PARENT_DIR setting in test/BOG_kelp18S/BOG_kelp18S_params.sh that points to a share on the mbonlive server.—

**Pull request merged**
